# Generated by Django 4.0.1 on 2022-10-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creds',
            old_name='verfied',
            new_name='verified',
        ),
    ]
