# Generated by Django 4.0.1 on 2022-10-19 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
