# Generated by Django 4.0.1 on 2022-10-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_apitoken_user_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
